services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.7
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./library:/config
      - ./tvseries:/tv
      - ./movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: no
