version: '3'

services:
  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: no
    network_mode: "host"
    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro
      - ./ssl/:/etc/nginx/ssl/:ro
